version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: ecommerce_postgres
    environment:
      POSTGRES_USER: sans
      POSTGRES_PASSWORD: sans
      POSTGRES_DB: sans-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_network

volumes:
  postgres_data:

networks:
  ecommerce_network:
